package src

import (
	"bytes"
	"encoding/binary"
	"fmt"
	"io"
	"log"
	"sort"
	"unicode"

	"github.com/go-text/typesetting-utils/generators/unicodedata/cmd/src/packtab"
	"golang.org/x/text/unicode/rangetable"
)

const unicodedataheader = `
// SPDX-License-Identifier: Unlicense OR BSD-3-Clause

package unicodedata

// Code generated by typesettings-utils/generators/unicodedata/cmd/main.go DO NOT EDIT.


`

func sortRunes(rs []rune) {
	sort.Slice(rs, func(i, j int) bool { return rs[i] < rs[j] })
}

func maxRunes(rs []rune) rune {
	maxRune := rs[0]
	for _, r := range rs {
		if r > maxRune {
			maxRune = r
		}
	}
	return maxRune
}

// runesToTable returns a crible where runes in [rs]
// have value 1, consumable by packtab
func runesToTable(rs []rune) []int {
	table := make([]int, maxRunes(rs)+1)
	for _, r := range rs {
		table[r] = 1
	}
	return table
}

func tableSize(rt *unicode.RangeTable) int {
	return 12*2 + 4 + len(rt.R16)*6 + len(rt.R32)*12
}

// compacts the code more than a "%#v" directive
func printTable(rt *unicode.RangeTable, omitTypeLitteral bool) string {
	w := new(bytes.Buffer)
	if omitTypeLitteral {
		fmt.Fprintln(w, "{")
	} else {
		fmt.Fprintln(w, "&unicode.RangeTable{")
	}
	if len(rt.R16) > 0 {
		fmt.Fprintln(w, "\tR16: []unicode.Range16{")
		for _, r := range rt.R16 {
			fmt.Fprintf(w, "\t\t{Lo:%#04x, Hi:%#04x, Stride:%d},\n", r.Lo, r.Hi, r.Stride)
		}
		fmt.Fprintln(w, "\t},")
	}
	if len(rt.R32) > 0 {
		fmt.Fprintln(w, "\tR32: []unicode.Range32{")
		for _, r := range rt.R32 {
			fmt.Fprintf(w, "\t\t{Lo:%#x, Hi:%#x,Stride:%d},\n", r.Lo, r.Hi, r.Stride)
		}
		fmt.Fprintln(w, "\t},")
	}
	if rt.LatinOffset > 0 {
		fmt.Fprintf(w, "\tLatinOffset: %d,\n", rt.LatinOffset)
	}
	fmt.Fprintf(w, "}")
	return w.String()
}

func generateCombiningClasses(classes map[uint8][]rune, w io.Writer) {
	fmt.Fprint(w, unicodedataheader)

	// create and compact the tables
	var out [256]*unicode.RangeTable
	for k, v := range classes {
		if len(v) == 0 {
			panic("empty combining class")
		}
		out[k] = rangetable.New(v...)
	}

	// print them
	totalSize := 0
	fmt.Fprintln(w, "var combiningClasses = [256]*unicode.RangeTable{")
	for i, rt := range out {
		if rt == nil {
			continue
		}
		size := tableSize(rt)
		fmt.Fprintf(w, "%d : %s, // size %d B. \n", i, printTable(rt, true), size)

		totalSize += size
	}
	fmt.Fprintln(w, "}")
	fmt.Fprintf(w, "// Total size %d KB.", totalSize/1000)
}

func generateCombiningClassesPacktab(db unicodeDatabase, w io.Writer) {
	table := make([]int, db.maxUnicode+1) // default to 0
	for _, char := range db.chars {
		table[char.char] = int(char.combiningClass)
	}
	code := packtab.PackTable(table, 0, 9).Code("ccc")

	fmt.Fprint(w, unicodedataheader)
	fmt.Fprintf(w, "// Unicode version: %s\n\n", version)

	fmt.Fprintln(w, code)
}

func generateEmojis(classes map[string][]rune, w io.Writer) {
	// among "Emoji", "Emoji_Presentation", "Emoji_Modifier", "Emoji_Modifier_Base", "Extended_Pictographic"
	// only Extended_Pictographic is actually used
	table := classes["Extended_Pictographic"]
	rt := rangetable.New(table...)

	fmt.Fprint(w, unicodedataheader)
	s := printTable(rt, false)
	fmt.Fprintf(w, "var Extended_Pictographic = %s\n\n", s)
	fmt.Fprintf(w, "// Total size %d B.", tableSize(rt))
}

func generateEmojisPacktab(classes map[string][]rune, w io.Writer) {
	// among "Emoji", "Emoji_Presentation", "Emoji_Modifier", "Emoji_Modifier_Base", "Extended_Pictographic"
	// only Extended_Pictographic is actually used

	table := runesToTable(classes["Extended_Pictographic"])

	fmt.Fprint(w, unicodedataheader)
	fmt.Fprintf(w, "// Unicode version: %s\n\n", version)

	code := packtab.PackTable(table, 0, 9).Code("emoji")
	fmt.Fprintln(w, code)
}

func generateMirroring(runes map[uint16]uint16, w io.Writer) {
	fmt.Fprint(w, unicodedataheader)
	fmt.Fprintf(w, "var mirroring = map[rune]rune{ // %d entries \n", len(runes))
	var sorted []rune
	for r1 := range runes {
		sorted = append(sorted, rune(r1))
	}
	sortRunes(sorted)
	for _, r1 := range sorted {
		r2 := runes[uint16(r1)]
		fmt.Fprintf(w, "0x%04x: 0x%04x,\n", r1, r2)
	}
	fmt.Fprintln(w, "}")
}

// Mirroring character is encoded as difference from
// the original character.
func generateMirroringPacktab(db unicodeDatabase, runes map[uint16]uint16, w io.Writer) {
	table := make([]int, db.maxUnicode+1) // default to 0
	for u, v := range runes {
		table[u] = int(v) - int(u)
	}

	fmt.Fprint(w, unicodedataheader)
	fmt.Fprintf(w, "// Unicode version: %s\n\n", version)

	code := packtab.PackTable(table, 0, 9).Code("mir")
	fmt.Fprintln(w, code)
}

func generateDecomposition(combiningClasses map[uint8][]rune, dms map[rune][]rune, compExp map[rune]bool, w io.Writer) {
	var (
		decompose1 [][2]rune         // length 1 mappings {from, to}
		decompose2 [][3]rune         // length 2 mappings {from, to1, to2}
		compose    [][3]rune         // length 2 mappings {from1, from2, to}
		ccc        = map[rune]bool{} // has combining class
	)
	for c, runes := range combiningClasses {
		for _, r := range runes {
			ccc[r] = c != 0
		}
	}
	for r, v := range dms {
		switch len(v) {
		case 1:
			decompose1 = append(decompose1, [2]rune{r, v[0]})
		case 2:
			decompose2 = append(decompose2, [3]rune{r, v[0], v[1]})
			var composed rune
			if !compExp[r] && !ccc[r] {
				composed = r
			}
			compose = append(compose, [3]rune{v[0], v[1], composed})
		default:
			log.Fatalf("unexpected runes for decomposition: %d, %v", r, v)
		}
	}

	// sort for determinisme
	sort.Slice(decompose1, func(i, j int) bool { return decompose1[i][0] < decompose1[j][0] })
	sort.Slice(decompose2, func(i, j int) bool { return decompose2[i][0] < decompose2[j][0] })
	sort.Slice(compose, func(i, j int) bool {
		return compose[i][0] < compose[j][0] ||
			compose[i][0] == compose[j][0] && compose[i][1] < compose[j][1]
	})

	fmt.Fprint(w, unicodedataheader)

	fmt.Fprintf(w, "var decompose1 = map[rune]rune{ // %d entries \n", len(decompose1))
	for _, vals := range decompose1 {
		fmt.Fprintf(w, "0x%04x: 0x%04x,\n", vals[0], vals[1])
	}
	fmt.Fprintln(w, "}")

	fmt.Fprintf(w, "var decompose2 = map[rune][2]rune{ // %d entries \n", len(decompose2))
	for _, vals := range decompose2 {
		fmt.Fprintf(w, "0x%04x: {0x%04x,0x%04x},\n", vals[0], vals[1], vals[2])
	}
	fmt.Fprintln(w, "}")

	fmt.Fprintf(w, "var compose = map[[2]rune]rune{ // %d entries \n", len(compose))
	for _, vals := range compose {
		fmt.Fprintf(w, "{0x%04x,0x%04x}: 0x%04x,\n", vals[0], vals[1], vals[2])
	}
	fmt.Fprintln(w, "}")
}

func codepointEncode3_11_7_14(x, y, z rune) int {
	return int((uint32(x)&0x07FF)<<21 | (uint32(y)&0x007F)<<14 | uint32(z)&0x3FFF)
}

func codepointEncode3(x, y, z rune) int {
	return int((uint64(x) << 42) | (uint64(y) << 21) | uint64(z))
}

func generateDecompositionPacktab(combiningClasses map[uint8][]rune, dms map[rune][]rune, compExp map[rune]bool, w io.Writer) {
	var (
		decompose1  [][2]rune         // length 1 mappings {from, to}
		decompose2  [][3]rune         // length 2 mappings {from, to1, to2}
		compose     [][3]rune         // length 2 mappings {from1, from2, to}
		ccc         = map[rune]bool{} // has combining class
		uniqDm1     = map[rune]bool{}
		maxRuneInDm rune
	)
	for c, runes := range combiningClasses {
		for _, r := range runes {
			ccc[r] = c != 0
		}
	}
	for r, v := range dms {
		if r > maxRuneInDm {
			maxRuneInDm = r
		}

		switch len(v) {
		case 1:
			decompose1 = append(decompose1, [2]rune{r, v[0]})
			uniqDm1[v[0]] = true
		case 2:
			decompose2 = append(decompose2, [3]rune{r, v[0], v[1]})
			var composed rune
			if !compExp[r] && !ccc[r] {
				composed = r
			}
			compose = append(compose, [3]rune{v[0], v[1], composed})
		default:
			log.Fatalf("unexpected runes for decomposition: %d, %v", r, v)
		}
	}

	// sort for determinisme
	sort.Slice(decompose1, func(i, j int) bool { return decompose1[i][0] < decompose1[j][0] })
	sort.Slice(decompose2, func(i, j int) bool { return decompose2[i][0] < decompose2[j][0] })
	sort.Slice(compose, func(i, j int) bool {
		return compose[i][0] < compose[j][0] ||
			compose[i][0] == compose[j][0] && compose[i][1] < compose[j][1] ||
			compose[i][0] == compose[j][0] && compose[i][1] == compose[j][1] && compose[i][2] < compose[j][2]
	})

	var dm1 []rune
	for r := range uniqDm1 {
		dm1 = append(dm1, r)
	}
	sortRunes(dm1)
	var (
		dm1P0Array  []int
		dm1P2Array  []int
		dm2U32Array []int
		dm2U64Array []int
		dm1Order    = map[rune]int{}
		dm2Order    = map[[2]rune]int{}
	)
	for i, v := range dm1 {
		switch v >> 16 {
		case 0:
			dm1P0Array = append(dm1P0Array, int(v&0xFFFF))
		case 2:
			dm1P2Array = append(dm1P2Array, int(v&0xFFFF))
		default:
			log.Fatalf("unexpected rune %0x", v)
		}
		dm1Order[v] = i + 1
	}
	for i, v := range compose {
		if v[0]&0x7FFFF800 == 0x0000 && v[1]&0x7FFFFF80 == 0x0300 && v[2]&0x7FF0C000 == 0x0000 {
			dm2U32Array = append(dm2U32Array, codepointEncode3_11_7_14(v[0], v[1], v[2]))
		} else {
			dm2U64Array = append(dm2U64Array, codepointEncode3(v[0], v[1], v[2]))
		}
		dm2Order[[2]rune{v[0], v[1]}] = i + 1 + len(dm1P0Array) + len(dm1P2Array)
	}

	// final mapping using order
	table := make([]int, maxRuneInDm+1)
	for _, v := range decompose1 {
		table[v[0]] = dm1Order[v[1]]
	}
	for _, v := range decompose2 {
		table[v[0]] = dm2Order[[2]rune{v[1], v[2]}]
	}

	fmt.Fprint(w, unicodedataheader)
	fmt.Fprintf(w, "// Unicode version: %s\n\n", version)

	dm1P0Map := packtab.Array{Type: "uint16", Values: dm1P0Array}
	dm1P2Map := packtab.Array{Type: "uint16", Values: dm1P2Array}
	dm2U32Map := packtab.Array{Type: "uint32", Values: dm2U32Array}
	dm2U64Map := packtab.Array{Type: "uint64", Values: dm2U64Array}
	packtab.PrintArray(w, "dm1P0Map", dm1P0Map, true)
	packtab.PrintArray(w, "dm1P2Map", dm1P2Map, true)
	packtab.PrintArray(w, "dm2U32Map", dm2U32Map, true)
	packtab.PrintArray(w, "dm2U64Map", dm2U64Map, true)

	fmt.Fprintf(w, "// Total size : %d B.\n\n", dm1P0Map.Size()+dm1P2Map.Size()+dm2U32Map.Size()+dm2U64Map.Size())

	dmCode := packtab.PackTable(table, 0, 9).Code("dm")
	fmt.Fprintln(w, dmCode)
}

func generateEastAsianWidth(datas map[string][]rune, w io.Writer) {
	fmt.Fprint(w, unicodedataheader)
	fmt.Fprintf(w, "// Unicode version: %s\n\n", version)

	// the table is used for UAX14 (LB30) : we group the classes
	// F (Fullwidth), W (Wide), H (Halfwidth)
	runes := append(append(datas["F"], datas["W"]...), datas["H"]...)
	table := rangetable.New(runes...)
	s := printTable(table, false)
	fmt.Fprintf(w, `
	// LargeEastAsian matches runes with East_Asian_Width property of 
	// F, W or H, and is used for UAX14, rule LB30.
	var LargeEastAsian = %s

	// Size %d B.`, s, tableSize(table))
}

func generateEastAsianWidthPacktab(datas map[string][]rune, w io.Writer) {
	// the table is used for UAX14 (LB30) : we group the classes
	// F (Fullwidth), W (Wide), H (Halfwidth)
	runes := append(append(datas["F"], datas["W"]...), datas["H"]...)
	table := runesToTable(runes)

	fmt.Fprint(w, unicodedataheader)
	fmt.Fprintf(w, "// Unicode version: %s\n\n", version)

	// this table is not so large, favour speed over size here
	dmCode := packtab.PackTable(table, 0, 1).Code("eastAsianWidth")
	fmt.Fprintln(w, dmCode)
}

func generateEmojisTest(sequences [][]rune, w io.Writer) {
	fmt.Fprintln(w, `
	// SPDX-License-Identifier: Unlicense OR BSD-3-Clause

	package harfbuzz

	// Code generated by typesettings-utils/generators/unicodedata/cmd/main.go DO NOT EDIT.

	`)

	fmt.Fprintln(w, "var emojisSequences = [][]rune{")
	for _, seq := range sequences {
		if len(seq) < 2 {
			continue
		}
		fmt.Fprint(w, "{")
		for _, r := range seq {
			fmt.Fprintf(w, "0x%x,", r)
		}
		fmt.Fprintln(w, "},")
	}
	fmt.Fprintln(w, "}")
}

type item struct {
	start, end rune
	script     string // name
}

func compactScriptLookupTable(scripts map[string][]runeRange, scriptNames map[string]uint32) []item {
	var crible []item
	for scriptName, runes := range scripts {
		_, ok := scriptNames[scriptName]
		if !ok {
			check(fmt.Errorf("unknown script name %s", scriptName))
		}
		for _, ra := range runes {
			crible = append(crible, item{script: scriptName, start: ra.Start, end: ra.End})
		}
	}

	sort.Slice(crible, func(i, j int) bool { return crible[i].start < crible[j].start })

	for i := range crible {
		if i == len(crible)-1 {
			continue
		}
		if crible[i].end >= crible[i+1].start {
			check(fmt.Errorf("inconsistent crible index %d: %v %v", i, crible[i], crible[i+1]))
		}
	}

	var compacted []item
	for _, v := range crible {
		if len(compacted) == 0 {
			compacted = append(compacted, v)
			continue
		}

		last := &compacted[len(compacted)-1]

		if v.script == last.script && v.start == last.end+1 { // merge
			last.end = v.end
		} else {
			compacted = append(compacted, v)
		}
	}

	return compacted
}

func scriptToString(s uint32) string {
	var buf [4]byte
	binary.BigEndian.PutUint32(buf[:], s)
	return string(buf[:])
}

func generateScriptLookupTable(scripts map[string][]runeRange, scriptNames map[string]uint32, w io.Writer) {
	crible := compactScriptLookupTable(scripts, scriptNames)

	fmt.Fprintln(w, `
	// SPDX-License-Identifier: Unlicense OR BSD-3-Clause

	package language

	// Code generated by typesettings-utils/generators/unicodedata/cmd/main.go DO NOT EDIT.

	`)

	// scripts constants
	fmt.Fprintln(w, "const (")

	var sortedKeys []string
	for k := range scriptNames {
		sortedKeys = append(sortedKeys, k)
	}
	sort.Strings(sortedKeys)

	for _, k := range sortedKeys {
		v := scriptNames[k]
		fmt.Fprintf(w, "%s = Script(0x%08x) // %s \n", k, v, scriptToString(v))
	}
	fmt.Fprintln(w, ")")

	fmt.Fprintln(w, `
	// scriptToTag is only used in tests and will be 
	// removed by the linker
	var scriptToTag = map[string]Script{`)
	for _, k := range sortedKeys {
		fmt.Fprintf(w, "%q : %s,\n", k, k)
	}
	fmt.Fprintln(w, "}")

	fmt.Fprintln(w, `
	// ScriptRange is an inclusive range of runes
 	// with constant script.
	type ScriptRange struct {
		Start, End rune
		Script     Script
	}
	
	// ScriptRanges is a sorted list of script ranges.
	var ScriptRanges = [...]ScriptRange{`)
	for _, item := range crible {
		fmt.Fprintf(w, "{0x%x, 0x%x, %s},\n", item.start, item.end, item.script)
	}
	fmt.Fprintln(w, "}")
}

func generateGeneralCategoriesPacktab(db unicodeDatabase, valueAliases map[string]string, w io.Writer) {
	// build the mapping string -> int
	enum := map[string]int{}
	for i, cat := range db.generalCategoryNames {
		enum[cat] = i + 1 // 0 if for unassigned
	}
	table := make([]int, db.maxUnicode+1) // default to 0
	for _, char := range db.chars {
		table[char.char] = enum[char.generalCategory]
	}
	code := packtab.PackTable(table, 0, 9).Code("gc")

	fmt.Fprint(w, unicodedataheader)
	fmt.Fprintf(w, "// Unicode version: %s\n\n", version)

	fmt.Fprintln(w, `
	const (
		Unassigned GeneralCategory = iota`)
	for _, cat := range db.generalCategoryNames {
		fmt.Fprintf(w, "%s // %s \n", cat, valueAliases[cat])
	}
	fmt.Fprintln(w, ")")

	fmt.Fprintln(w, code)
}
